# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["Daniel Verrall"]
description = "Example Fastly Compute application using expressly-otel-middleware"
language = "javascript"
manifest_version = 3
name = "expressly-otel-example"
service_id = ""

[local_server]

[local_server.backends]

[local_server.backends.otlp-collector]
  url = "http://localhost:4318"

[scripts]
  build = "yarn build"
  post_init = "yarn"
